from typing import Protocol

from src.domain.entities import Member, Task, Team
from src.domain.enums import TaskStatus


class TeamRepository(Protocol):
    def add(self, team: Team) -> Team: ...

    def get(self, team_id: int) -> Team | None: ...

    def list_all(self) -> list[Team]: ...


class TaskRepository(Protocol):
    def add(self, task: Task) -> Task: ...

    def get(self, task_id: int) -> Task | None: ...

    def list_by_team(self, team_id: int) -> list[Task]: ...

    def update_status(self, task_id: int,
                      status: TaskStatus) -> Task | None: ...

    def update_assignee(self, task_id: int,
                        assignee_id: int | None) -> Task | None: ...


class MemberRepository(Protocol):
    def add(self, member: Member) -> Member: ...

    def get_by_id(self, member_id: int) -> Member | None: ...

    def get_by_email(self, email: str) -> Member | None: ...

    def list_all(self) -> list[Member]: ...
